import Foundation

/// The public, file-based contract between FocusTrace and a Codex scheduled
/// task. FocusTrace prepares this workspace locally; Codex only sees the
/// aggregate reports produced inside it.
public enum CodexWorkspaceContract {
    public static let workspaceDirectoryName = "CodexWorkspace"
    public static let reportDirectoryName = "Reports"

    public static let setupPrompt = """
    请帮我完成 FocusTrace 的 Codex 每日行动复盘接入。

    先阅读当前工作区的 AGENTS.md，并立即执行一次其中的“每日复盘流程”来验证文件桥。验证成功后，创建一个名为“FocusTrace 每日行动复盘”的定时任务：每天 18:35 在当前本地工作区执行同一套每日复盘流程。

    必须遵守 AGENTS.md 的隐私边界：只读取聚合报告，不读取 FocusTrace 原始活动数据，也不修改训练计划、允许应用、通知或其他偏好。完成后简要告诉我本次验证结果和定时任务状态。
    """

    public static let agentsInstructions = """
    # FocusTrace Codex workspace instructions

    ## Scope

    This generated workspace is only for FocusTrace aggregate daily reviews.
    Use “工作流” in user-facing Chinese. Treat FocusTrace as work-behavior
    tracking and focus-habit training, not ADHD diagnosis or treatment.

    ## Privacy boundary

    - Start every run with `./Scripts/generate-daily-report.sh`.
    - Read only `Reports/latest.json` and `Reports/latest.md`.
    - Never read or expose FocusTrace `store.json`, raw activity rows, Bundle
      IDs, event IDs, window titles, URLs, input content, or task recovery text.
    - Never modify FocusTrace training plans, allowed applications, notification
      settings, work schedules, or other preferences.
    - If report generation fails, stop and report the local error. Do not search
      for raw data as a fallback.

    ## 每日复盘流程

    1. Run `./Scripts/generate-daily-report.sh`.
    2. Read only `Reports/latest.json` and `Reports/latest.md`.
    3. Turn the report into a decision brief, not a summary. Answer only:
       - 当前最重要的问题是什么？
       - 今天具体怎么解决？

       Select exactly one problem in this order:
       - If `dataQuality.isReliableForBehavior` is false, select the highest
         priority data-quality blocker. Do not make a behavior or attention
         claim.
       - Otherwise, prefer a `previousRecommendationEvaluation` whose status is
         `needsAdjustment` or `notRun`.
       - Otherwise, use the strongest current normalized trend or the report's
         single `recommendation`.

       The action must be executable today. State its trigger and concrete
       behavior; use the report's `recommendation.method.steps` and
       `successMeasure` rather than inventing an unrelated productivity tip.
    4. Write `Reports/codex-draft.json` with exactly these fields:

       ```json
       {
         "schemaVersion": 2,
         "sourceReportID": "copy reportID from latest.json",
         "reportDate": "copy reportDate from latest.json exactly",
         "generatedAt": "current ISO 8601 timestamp with timezone",
         "status": "behaviorFinding or dataQualityBlocked",
         "problem": "one sentence naming the single problem and its measured consequence",
         "recommendation": "one concrete action to perform today",
         "evidence": ["one or two non-duplicated aggregate facts"],
         "nextCheck": "when to check one metric and its target"
       }
       ```

       Hard writing rules:
       - If behavior reliability is false, use `dataQualityBlocked` and include
         the exact phrase “当前不能据此判断注意力” in `problem`. The recommendation
         must repair that one data problem.
       - If behavior reliability is true, use `behaviorFinding`.
       - `problem` is at most 110 Chinese characters; `recommendation` at most
         150; each evidence item at most 80; `nextCheck` at most 80.
       - The four displayed parts together are at most 360 characters.
       - Evidence must be a fact from the aggregate report, not another opinion,
         and the two items must not restate each other.
       - Do not add a preface, privacy explanation, generic trend summary,
         motivational sentence, or a second recommendation.
       - Do not discuss Phase 2 unlock progress unless an unlocked Phase 2
         insight is the selected problem.
       - Avoid filler such as “总体来看”, “值得注意”, “建议继续关注” and
         “保持当前节奏”.

    5. Validate and install it with:

       ```bash
       /usr/bin/python3 Scripts/install-codex-review.py \
         --report Reports/latest.json \
         --review Reports/codex-draft.json \
         --output-dir Reports
       ```

    6. Reply with only the problem and today's action. Do not paste the full
       JSON unless asked.
    """

    public static let workspaceReadme = """
    # FocusTrace × Codex

    This folder is generated by FocusTrace for its optional daily Codex review.
    The app can rebuild the tools and instructions here when you reconnect.

    - `Scripts/generate-daily-report.sh` creates aggregate-only input.
    - `Reports/latest.json` and `Reports/latest.md` are the only review inputs.
    - `Scripts/install-codex-review.py` validates Codex's aggregate-only output.
    - FocusTrace displays the validated `Reports/codex-YYYY-MM-DD.json`.

    No API key is required. Keep the ChatGPT desktop app running when the
    scheduled task needs to access this local workspace.
    """

    public static let reportScript = #"""
    #!/bin/bash
    set -euo pipefail

    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
    REPORT_TOOL="$WORKSPACE_ROOT/Tools/FocusTraceReport"
    REPORT_DIR="$WORKSPACE_ROOT/Reports"
    STORE_PATH="${FOCUSTRACE_STORE_PATH:-$HOME/Library/Application Support/FocusTrace/store.json}"
    BRIDGE_DIR="$HOME/Library/Application Support/FocusTrace/CodexBridge"

    if [[ ! -x "$REPORT_TOOL" ]]; then
      echo "error: FocusTraceReport 工具缺失，请回到 FocusTrace 点击“在 Codex 中接入每日复盘”重建工作区" >&2
      exit 1
    fi

    mkdir -p "$REPORT_DIR" "$BRIDGE_DIR"
    "$REPORT_TOOL" --store "$STORE_PATH" --output-dir "$REPORT_DIR" "$@"

    /usr/bin/python3 - "$BRIDGE_DIR/bridge.json" "$REPORT_DIR" <<'PY'
    import datetime
    import json
    import os
    import pathlib
    import sys

    destination, report_directory = sys.argv[1:]
    destination_path = pathlib.Path(destination)
    temporary_path = destination_path.with_suffix(".tmp")
    payload = {
        "schemaVersion": 1,
        "reportDirectory": str(pathlib.Path(report_directory).resolve()),
        "updatedAt": datetime.datetime.now(datetime.timezone.utc).isoformat(
            timespec="seconds"
        ).replace("+00:00", "Z"),
    }
    temporary_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    os.replace(temporary_path, destination_path)
    PY

    echo "FocusTrace Codex 文件桥已连接：$BRIDGE_DIR/bridge.json"
    """#

    public static func deepLink(workspaceURL: URL) -> URL? {
        var components = URLComponents()
        components.scheme = "codex"
        components.host = "threads"
        components.path = "/new"
        components.queryItems = [
            URLQueryItem(name: "path", value: workspaceURL.standardizedFileURL.path),
            URLQueryItem(name: "prompt", value: setupPrompt)
        ]
        return components.url
    }
}
